// item-map.js
// Server-side copy of the ITEM_MAP living in public/js/builds.js (frontend,
// browser-only — there's no way for index.js to reach it directly). Used by
// the "Ask a build" Discord button (see index.js) to resolve a weapon name
// into an Albion render ID for the embed thumbnail.
//
// IMPORTANT: this is a manually-kept-in-sync duplicate, not a shared import.
// If items are added to public/js/builds.js's ITEM_MAP, add them here too.
// (Flagged in the C hand-off — a future refactor could load this from a
// single JSON file both sides require, but that's out of scope for now.)

const ITEM_MAP = {
  // Weapons
  "Broadsword": "T8_MAIN_SWORD",
  "Claymore": "T8_2H_CLAYMORE",
  "Dual Swords": "T8_2H_DUALSWORD",
  "Clarent Blade": "T8_MAIN_SCIMITAR_MORGANA",
  "Carving Sword": "T8_2H_CLEAVER_HELL",
  "Galatine Pair": "T8_2H_DUALSCIMITAR_UNDEAD",
  "Kingmaker": "T8_2H_CLAYMORE_AVALON",
  "Infinity Blade": "T8_MAIN_SWORD_CRYSTAL",
  "Battleaxe": "T8_MAIN_AXE",
  "Great Axe": "T8_2H_AXE",
  "Halberd": "T8_2H_HALBERD",
  "Carrioncaller": "T8_2H_HALBERD_MORGANA",
  "Infernal Scythe": "T8_2H_SCYTHE_HELL",
  "Bear Paws": "T8_2H_DUALAXE_KEEPER",
  "Realmbreaker": "T8_2H_AXE_AVALON",
  "Crystal Reaper": "T8_2H_SCYTHE_CRYSTAL",
  "Mace": "T8_MAIN_MACE",
  "Heavy Mace": "T8_2H_MACE",
  "Morning Star": "T8_2H_FLAIL",
  "Bedrock Mace": "T8_MAIN_ROCKMACE_KEEPER",
  "Incubus Mace": "T8_MAIN_MACE_HELL",
  "Camlann Mace": "T8_2H_MACE_MORGANA",
  "Oathkeepers": "T8_2H_DUALMACE_AVALON",
  "Dreadstorm Monarch": "T8_MAIN_MACE_CRYSTAL",
  "Hammer": "T8_MAIN_HAMMER",
  "Polehammer": "T8_2H_POLEHAMMER",
  "Great Hammer": "T8_2H_HAMMER",
  "Tombhammer": "T8_2H_HAMMER_UNDEAD",
  "Forge Hammers": "T8_2H_DUALHAMMER_HELL",
  "Grovekeeper": "T8_2H_RAM_KEEPER",
  "Hand of Justice": "T8_2H_HAMMER_AVALON",
  "Truebolt Hammer": "T8_2H_HAMMER_CRYSTAL",
  "Crossbow": "T8_2H_CROSSBOW",
  "Heavy Crossbow": "T8_2H_CROSSBOWLARGE",
  "Light Crossbow": "T8_MAIN_1HCROSSBOW",
  "Weeping Repeater": "T8_2H_REPEATINGCROSSBOW_UNDEAD",
  "Boltcasters": "T8_2H_DUALCROSSBOW_HELL",
  "Siegebow": "T8_2H_CROSSBOWLARGE_MORGANA",
  "Energy Shaper": "T8_2H_CROSSBOW_CANNON_AVALON",
  "Arclight Blasters": "T8_2H_DUALCROSSBOW_CRYSTAL",
  "Brawler Gloves": "T8_2H_KNUCKLES_SET1",
  "Battler Bracers": "T8_2H_KNUCKLES_SET2",
  "Spiked Gauntlets": "T8_2H_KNUCKLES_SET3",
  "Ursine Maulers": "T8_2H_KNUCKLES_KEEPER",
  "Hellfire Hands": "T8_2H_KNUCKLES_HELL",
  "Ravenstrike Cestus": "T8_2H_KNUCKLES_MORGANA",
  "Fists of Avalon": "T8_2H_KNUCKLES_AVALON",
  "Forcepulse Bracers": "T8_2H_KNUCKLES_CRYSTAL",
  "Bow": "T8_2H_BOW",
  "Warbow": "T8_2H_WARBOW",
  "Longbow": "T8_2H_LONGBOW",
  "Whispering Bow": "T8_2H_LONGBOW_UNDEAD",
  "Wailing Bow": "T8_2H_BOW_HELL",
  "Bow of Badon": "T8_2H_BOW_KEEPER",
  "Mistpiercer": "T8_2H_BOW_AVALON",
  "Skystrider Bow": "T8_2H_BOW_CRYSTAL",
  "Dagger": "T8_MAIN_DAGGER",
  "Dagger Pair": "T8_2H_DAGGERPAIR",
  "Claws": "T8_2H_CLAWPAIR",
  "Bloodletter": "T8_MAIN_RAPIER_MORGANA",
  "Demonfang": "T8_MAIN_DAGGER_HELL",
  "Deathgivers": "T8_2H_DUALSICKLE_UNDEAD",
  "Bridled Fury": "T8_2H_DAGGER_KATAR_AVALON",
  "Twin Slayers": "T8_2H_DAGGERPAIR_CRYSTAL",
  "Spear": "T8_MAIN_SPEAR",
  "Pike": "T8_2H_SPEAR",
  "Glaive": "T8_2H_GLAIVE",
  "Heron Spear": "T8_MAIN_SPEAR_KEEPER",
  "Spirithunter": "T8_2H_HARPOON_HELL",
  "Trinity Spear": "T8_2H_TRIDENT_UNDEAD",
  "Daybreaker": "T8_MAIN_SPEAR_LANCE_AVALON",
  "Rift Glaive": "T8_2H_GLAIVE_CRYSTAL",
  "Quarterstaff": "T8_2H_QUARTERSTAFF",
  "Ironclad Staff": "T8_2H_IRONCLADEDSTAFF",
  "Double Bladed Staff": "T8_2H_DOUBLEBLADEDSTAFF",
  "Black Monk Stave": "T8_2H_COMBATSTAFF_MORGANA",
  "Soulscythe": "T8_2H_TWINSCYTHE_HELL",
  "Staff of Balance": "T8_2H_ROCKSTAFF_KEEPER",
  "Grailseeker": "T8_2H_QUARTERSTAFF_AVALON",
  "Phantom Twinblade": "T8_2H_DOUBLEBLADEDSTAFF_CRYSTAL",
  "Nature Staff": "T8_MAIN_NATURESTAFF",
  "Great Nature Staff": "T8_2H_NATURESTAFF",
  "Wild Staff": "T8_2H_WILDSTAFF",
  "Druidic Staff": "T8_MAIN_NATURESTAFF_KEEPER",
  "Blight Staff": "T8_2H_NATURESTAFF_HELL",
  "Rampant Staff": "T8_2H_NATURESTAFF_KEEPER",
  "Ironroot Staff": "T8_MAIN_NATURESTAFF_AVALON",
  "Forgebark Staff": "T8_MAIN_NATURESTAFF_CRYSTAL",
  "Prowling Staff": "T8_2H_SHAPESHIFTER_SET1",
  "Rootbound Staff": "T8_2H_SHAPESHIFTER_SET2",
  "Primal Staff": "T8_2H_SHAPESHIFTER_SET3",
  "Bloodmoon Staff": "T8_2H_SHAPESHIFTER_MORGANA",
  "Hellspawn Staff": "T8_2H_SHAPESHIFTER_HELL",
  "Earthrune Staff": "T8_2H_SHAPESHIFTER_KEEPER",
  "Lightcaller": "T8_2H_SHAPESHIFTER_AVALON",
  "Stillgaze Staff": "T8_2H_SHAPESHIFTER_CRYSTAL",
  "Fire Staff": "T8_MAIN_FIRESTAFF",
  "Great Fire Staff": "T8_2H_FIRESTAFF",
  "Infernal Staff": "T8_2H_INFERNOSTAFF",
  "Wildfire Staff": "T8_MAIN_FIRESTAFF_KEEPER",
  "Brimstone Staff": "T8_2H_FIRESTAFF_HELL",
  "Blazing Staff": "T8_2H_INFERNOSTAFF_MORGANA",
  "Dawnsong": "T8_2H_FIRE_RINGPAIR_AVALON",
  "Flamewalker Staff": "T8_MAIN_FIRESTAFF_CRYSTAL",
  "Holy Staff": "T8_MAIN_HOLYSTAFF",
  "Great Holy Staff": "T8_2H_HOLYSTAFF",
  "Divine Staff": "T8_2H_DIVINESTAFF",
  "Lifetouch Staff": "T8_MAIN_HOLYSTAFF_MORGANA",
  "Fallen Staff": "T8_2H_HOLYSTAFF_HELL",
  "Redemption Staff": "T8_2H_HOLYSTAFF_UNDEAD",
  "Hallowfall": "T8_MAIN_HOLYSTAFF_AVALON",
  "Exalted Staff": "T8_2H_HOLYSTAFF_CRYSTAL",
  "Arcane Staff": "T8_MAIN_ARCANESTAFF",
  "Great Arcane Staff": "T8_2H_ARCANESTAFF",
  "Enigmatic Staff": "T8_2H_ENIGMATICSTAFF",
  "Witchwork Staff": "T8_MAIN_ARCANESTAFF_UNDEAD",
  "Occult Staff": "T8_2H_ARCANESTAFF_HELL",
  "Malevolent Locus": "T8_2H_ENIGMATICORB_MORGANA",
  "Evensong": "T8_2H_ARCANE_RINGPAIR_AVALON",
  "Astral Staff": "T8_2H_ARCANESTAFF_CRYSTAL",
  "Frost Staff": "T8_MAIN_FROSTSTAFF",
  "Great Frost Staff": "T8_2H_FROSTSTAFF",
  "Glacial Staff": "T8_2H_GLACIALSTAFF",
  "Hoarfrost Staff": "T8_MAIN_FROSTSTAFF_KEEPER",
  "Icicle Staff": "T8_2H_ICEGAUNTLETS_HELL",
  "Permafrost Prism": "T8_2H_ICECRYSTAL_UNDEAD",
  "Chillhowl": "T8_MAIN_FROSTSTAFF_AVALON",
  "Arctic Staff": "T8_2H_FROSTSTAFF_CRYSTAL",
  "Cursed Staff": "T8_MAIN_CURSEDSTAFF",
  "Great Cursed Staff": "T8_2H_CURSEDSTAFF",
  "Demonic Staff": "T8_2H_DEMONICSTAFF",
  "Lifecurse Staff": "T8_MAIN_CURSEDSTAFF_UNDEAD",
  "Cursed Skull": "T8_2H_SKULLORB_HELL",
  "Damnation Staff": "T8_2H_CURSEDSTAFF_MORGANA",
  "Shadowcaller": "T8_MAIN_CURSEDSTAFF_AVALON",
  "Rotcaller Staff": "T8_MAIN_CURSEDSTAFF_CRYSTAL",
  // Offhand
  "Shield": "T8_OFF_SHIELD",
  "Sarcophagus": "T8_OFF_TOWERSHIELD_UNDEAD",
  "Caitiff Shield": "T8_OFF_SHIELD_HELL",
  "Facebreaker": "T8_OFF_SPIKEDSHIELD_MORGANA",
  "Astral Aegis": "T8_OFF_SHIELD_AVALON",
  "Unbreakable Ward": "T8_OFF_SHIELD_CRYSTAL",
  "Torch": "T8_OFF_TORCH",
  "Mistcaller": "T8_OFF_HORN_KEEPER",
  "Sacred Scepter": "T8_OFF_TALISMAN_AVALON",
  "Cryptcandle": "T8_OFF_LAMP_UNDEAD",
  "Leering Cane": "T8_OFF_JESTERCANE_HELL",
  "Blueflame Torch": "T8_OFF_TORCH_CRYSTAL",
  "Tome of spells": "T8_OFF_BOOK",
  "Eye of Secrets": "T8_OFF_ORB_MORGANA",
  "Muisak": "T8_OFF_DEMONSKULL_HELL",
  "Taproot": "T8_OFF_TOTEM_KEEPER",
  "Celestial Censer": "T8_OFF_CENSER_AVALON",
  "Timelocked Grimoire": "T8_OFF_TOME_CRYSTAL",
  // Headpiece
  "Soldier Helmet": "T8_HEAD_PLATE_SET1",
  "Knight Helmet": "T8_HEAD_PLATE_SET2",
  "Guardian Helmet": "T8_HEAD_PLATE_SET3",
  "Graveguard Helmet": "T8_HEAD_PLATE_UNDEAD",
  "Demon Helmet": "T8_HEAD_PLATE_HELL",
  "Judicator Helmet": "T8_HEAD_PLATE_KEEPER",
  "Duskweaver Helmet": "T8_HEAD_PLATE_FEY",
  "Helmet of Valor": "T8_HEAD_PLATE_AVALON",
  "Royal Helmet": "T8_HEAD_PLATE_ROYAL",
  "Mercenary Hood": "T8_HEAD_LEATHER_SET1",
  "Hunter Hood": "T8_HEAD_LEATHER_SET2",
  "Assassin Hood": "T8_HEAD_LEATHER_SET3",
  "Stalker Hood": "T8_HEAD_LEATHER_MORGANA",
  "Hellion Hood": "T8_HEAD_LEATHER_HELL",
  "Specter Hood": "T8_HEAD_LEATHER_UNDEAD",
  "Mistwalker Hood": "T8_HEAD_LEATHER_FEY",
  "Hood of Tenacity": "T8_HEAD_LEATHER_AVALON",
  "Royal Hood": "T8_HEAD_LEATHER_ROYAL",
  "Scholar Cowl": "T8_HEAD_CLOTH_SET1",
  "Cleric Cowl": "T8_HEAD_CLOTH_SET2",
  "Mage Cowl": "T8_HEAD_CLOTH_SET3",
  "Druid Cowl": "T8_HEAD_CLOTH_KEEPER",
  "Fiend Cowl": "T8_HEAD_CLOTH_HELL",
  "Cultist Cowl": "T8_HEAD_CLOTH_MORGANA",
  "Feyscale Hat": "T8_HEAD_CLOTH_FEY",
  "Cowl of Purity": "T8_HEAD_CLOTH_AVALON",
  "Royal Cowl": "T8_HEAD_CLOTH_ROYAL",
  // Chest Piece
  "Soldier Armor": "T8_ARMOR_PLATE_SET1",
  "Knight Armor": "T8_ARMOR_PLATE_SET2",
  "Guardian Armor": "T8_ARMOR_PLATE_SET3",
  "Graveguard Armor": "T8_ARMOR_PLATE_UNDEAD",
  "Demon Armor": "T8_ARMOR_PLATE_HELL",
  "Judicator Armor": "T8_ARMOR_PLATE_KEEPER",
  "Duskweaver Armor": "T8_ARMOR_PLATE_FEY",
  "Armor of Valor": "T8_ARMOR_PLATE_AVALON",
  "Royal Armor": "T8_ARMOR_PLATE_ROYAL",
  "Mercenary Jacket": "T8_ARMOR_LEATHER_SET1",
  "Hunter Jacket": "T8_ARMOR_LEATHER_SET2",
  "Assassin Jacket": "T8_ARMOR_LEATHER_SET3",
  "Stalker Jacket": "T8_ARMOR_LEATHER_MORGANA",
  "Hellion Jacket": "T8_ARMOR_LEATHER_HELL",
  "Specter Jacket": "T8_ARMOR_LEATHER_UNDEAD",
  "Mistwalker Jacket": "T8_ARMOR_LEATHER_FEY",
  "Jacket of Tenacity": "T8_ARMOR_LEATHER_AVALON",
  "Royal Jacket": "T8_ARMOR_LEATHER_ROYAL",
  "Scholar Robe": "T8_ARMOR_CLOTH_SET1",
  "Cleric Robe": "T8_ARMOR_CLOTH_SET2",
  "Mage Robe": "T8_ARMOR_CLOTH_SET3",
  "Druid Robe": "T8_ARMOR_CLOTH_KEEPER",
  "Fiend Robe": "T8_ARMOR_CLOTH_HELL",
  "Cultist Robe": "T8_ARMOR_CLOTH_MORGANA",
  "Feyscale Robe": "T8_ARMOR_CLOTH_FEY",
  "Robe of Purity": "T8_ARMOR_CLOTH_AVALON",
  "Royal Robe": "T8_ARMOR_CLOTH_ROYAL",
  // Footwear
  "Soldier Boots": "T8_SHOES_PLATE_SET1",
  "Knight Boots": "T8_SHOES_PLATE_SET2",
  "Guardian Boots": "T8_SHOES_PLATE_SET3",
  "Graveguard Boots": "T8_SHOES_PLATE_UNDEAD",
  "Demon Boots": "T8_SHOES_PLATE_HELL",
  "Judicator Boots": "T8_SHOES_PLATE_KEEPER",
  "Duskweaver Boots": "T8_SHOES_PLATE_FEY",
  "Boots of Valor": "T8_SHOES_PLATE_AVALON",
  "Royal Boots": "T8_SHOES_PLATE_ROYAL",
  "Mercenary Shoes": "T8_SHOES_LEATHER_SET1",
  "Hunter Shoes": "T8_SHOES_LEATHER_SET2",
  "Assassin Shoes": "T8_SHOES_LEATHER_SET3",
  "Stalker Shoes": "T8_SHOES_LEATHER_MORGANA",
  "Hellion Shoes": "T8_SHOES_LEATHER_HELL",
  "Specter Shoes": "T8_SHOES_LEATHER_UNDEAD",
  "Mistwalker Shoes": "T8_SHOES_LEATHER_FEY",
  "Shoes of Tenacity": "T8_SHOES_LEATHER_AVALON",
  "Royal Shoes": "T8_SHOES_LEATHER_ROYAL",
  "Scholar Sandals": "T8_SHOES_CLOTH_SET1",
  "Cleric Sandals": "T8_SHOES_CLOTH_SET2",
  "Mage Sandals": "T8_SHOES_CLOTH_SET3",
  "Druid Sandals": "T8_SHOES_CLOTH_KEEPER",
  "Fiend Sandals": "T8_SHOES_CLOTH_HELL",
  "Cultist Sandals": "T8_SHOES_CLOTH_MORGANA",
  "Feyscale Sandals": "T8_SHOES_CLOTH_FEY",
  "Sandals of Purity": "T8_SHOES_CLOTH_AVALON",
  "Royal Sandals": "T8_SHOES_CLOTH_ROYAL",
  // Cape
  "Bridgewatch Cape": "T8_CAPEITEM_FW_BRIDGEWATCH",
  "Martlock Cape": "T8_CAPEITEM_FW_MARTLOCK",
  "Thetford Cape": "T8_CAPEITEM_FW_THETFORD",
  "Fort Sterling Cape": "T8_CAPEITEM_FW_FORTSTERLING",
  "Lymhurst Cape": "T8_CAPEITEM_FW_LYMHURST",
  "Caerleon Cape": "T8_CAPEITEM_FW_CAERLEON",
  "Brecilien Cape": "T8_CAPEITEM_FW_BRECILIEN",
  "Avalonian Cape": "T8_CAPEITEM_AVALON",
  "Heretic Cape": "T8_CAPEITEM_HERETIC",
  "Undead Cape": "T8_CAPEITEM_UNDEAD",
  "Keeper Cape": "T8_CAPEITEM_KEEPER",
  "Morgana Cape": "T8_CAPEITEM_MORGANA",
  "Demon Cape": "T8_CAPEITEM_DEMON",
  "Smuggler Cape": "T8_CAPEITEM_SMUGGLER",
  // Potion
  "Poison Potion": "T8_POTION_COOLDOWN",
  "Invisibility Potion": "T8_POTION_CLEANSE",
  "Berserk Potion": "T8_POTION_BERSERK",
  "Hellfire Potion": "T8_POTION_LAVA",
  "Gathering Potion": "T8_POTION_GATHER",
  "Tornado in a Bottle": "T8_POTION_TORNADO",
  "Gigantify Potion": "T7_POTION_REVIVE",
  "Resistance Potion": "T7_POTION_STONESKIN",
  "Sticky Potion": "T7_POTION_SLOWFIELD",
  "Calming Potion": "T7_POTION_MOB_RESET",
  "Cleansing Potion": "T7_POTION_CLEANSE2",
  "Acid Potion": "T7_POTION_ACID",
  "Healing Potion": "T6_POTION_HEAL",
  "Energy Potion": "T6_POTION_ENERGY",
  // Food
  "Pork Pie": "T7_MEAL_PIE",
  "Pork Omelette": "T7_MEAL_OMELETTE",
  "Dusthole Crab Omelette": "T7_MEAL_OMELETTE_FISH",
  "Avalonian Pork Omelette": "T7_MEAL_OMELETTE_AVALON",
  "Beef Stew": "T8_MEAL_STEW",
  "Deadwater Eel Stew": "T8_MEAL_STEW_FISH",
  "Beef Sandwich": "T8_MEAL_SANDWICH",
  "Thunderfall Lurcher Sandwich": "T8_MEAL_SANDWICH_FISH",
  "Avalonian Beef Sandwich": "T8_MEAL_SANDWICH_AVALON",
  "Roast Pork": "T7_MEAL_ROAST",
  "Roasted Puremist Snapper": "T7_MEAL_ROAST_FISH",
};

function itemImageUrl(name) {
  const id = ITEM_MAP[name];
  return id ? `https://render.albiononline.com/v1/item/${id}.png?quality=1` : null;
}

module.exports = { ITEM_MAP, itemImageUrl };
